### ISSUE TITLE
Check product stock - 500 (Internal Server Error) 

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront-api#10]
Scenario: 

Click on add to cart button:

![2017-12-11_10-08-34](https://user-images.githubusercontent.com/414067/33817902-783da0d6-de5b-11e7-8b85-21b08a96e0b6.png)

Mon, 11 Dec 2017 06:05:49 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at src/api/stock.js:39:12
Mon, 11 Dec 2017 06:05:49 GMT express deprecated req.param(name): Use req.params, req.body, or req.query instead at src/api/stock.js:41:24
debug: Calling API endpoint: GET http://m.local/V1/stockItems/MS11-XS-Blue
debug:  url=http://m.local/V1/stockItems/MS11-XS-Blue, method=GET, Authorization=OAuth oauth_consumer_key="uq9yhhs6c9qs4pi19fip2c189sedpxha", oauth_nonce="bSoMCDFWdWMnV3ukWax2c9JXQ9mYyMnO", oauth_signature="xtNapmnrU6kj1geuYwpPQuoMKUM%3D", oauth_signature_method="HMAC-SHA1", oauth_timestamp="1512972349", oauth_token="jxbi2dfacjt2xvjpbvnw71gb891oqwn3", oauth_version="1.0", json=true, body=undefined
debugGET /api/stock/check/MS11-XS-Blue : Response received.
500 812.110 ms - 44
error: API call failed: HTTP ERROR undefined

See incorrect endpoint 
`http://m.local/V1/stockItems/MS11-XS-Blue`

Should be:
`http://m.local/rest/V1/stockItems/MS11-XS-Blue`

**Comment by pkarw** [comment]
There is issue with config.example.json
'magento2.api' should be http://m.local/rest/

'magento2.url' is required for other purposes (should be magento2 base url)

No code changes are required then.

**Comment by dimasch** [comment]
@pkarw Nice!

I fix this pull.

**Comment by pkarw** [comment]
Fixed with https://github.com/DivanteLtd/vue-storefront-api/commit/649fa17dc008aa3c6d81ceb77819d8c07243f081

**Comment by dimasch** [comment]
@pkarw Should be `/` in end of line:

https://github.com/DivanteLtd/vue-storefront-api/blob/649fa17dc008aa3c6d81ceb77819d8c07243f081/src/config.example.json#L35

http://demo-magento2.vuestorefront.io/rest/

**Comment by pkarw** [comment]
Magento rest client already adds slash (check rest_client.is), should be fine without it

**Comment by dimasch** [comment]
@pkarw 

Yes, you right. But it not work in other import orders script

https://github.com/DivanteLtd/vue-storefront-api/blob/649fa17dc008aa3c6d81ceb77819d8c07243f081/src/worker/order_to_magento2.js#L44

https://github.com/DivanteLtd/vue-storefront-api/blob/649fa17dc008aa3c6d81ceb77819d8c07243f081/src/worker/order_to_magento2.js#L40

In config.magento2.url setted http://magento2.demo-1.xyz.com -- without rest/

**Comment by pkarw** [comment]
You're right! Could you fix it please?

**Comment by dimasch** [comment]
@pkarw Ready!
Have a nice day)
