### ISSUE TITLE
Elastic Search Forces HTTP

### ISSUE THREAD

**Issue by WazzaJB** [DivanteLtd/vue-storefront-api#108]
Hey,

Been working on getting this into production for some proper testing (looks great locally, good work!).

So we've set up our AWS VPC alongside ElastiCache (Redis), EC2 for Node and Elasticsearch.

Unfortunately it seems we can't configure HTTPS for ElasticSearch requests which is somewhat hindering us as this is how AWS serves it.

I've tried modifying the ES client calls (such as src/graphql/elasticsearch/client.js) and adding a protocol option from config.json without any luck sadly.

```
const client = new elasticsearch.Client({
  hosts: [
    config.elasticsearch.protocol + '://' + config.elasticsearch.host + ':' + config.elasticsearch.port
  ]
});
```

```
  "elasticsearch": {
    "host": "<elastic>.amazonaws.com",
    "protocol": "https",
    "port": 9200,
    "indices": [
      "vue_storefront_catalog"
    ]
  },
```

<img width="300" alt="screen shot 2018-09-13 at 17 23 21" src="https://user-images.githubusercontent.com/2930904/45501679-c3e09000-b779-11e8-8ccc-1c508bf79e85.png">

Any pointers?

Thanks again.

**Comment by pkarw** [comment]
Hi You can use full URL with protocol in the elasticsearch.host - it should be fine then

**Comment by hunterjamesio** [comment]
Hey @pkarw 

It doesn't look like that is the case?

The URL is currently pieced together like this:

```js
	let url = 'http://' + config.elasticsearch.host + ':' + config.elasticsearch.port + (req.query.request ? _updateQueryStringParameter(req.url, 'request', null) : req.url)

```

Thus forcing the HTTP prefix. I ended up just modifying every where the ES URL is built to also handle a protocol parameter from config that defaults to http. Can submit a pull request if we are in agreement?

**Comment by pkarw** [comment]
Haha it has been just fixed and merged to develop 10minutes a go :)

**Comment by hunterjamesio** [comment]
Great stuff :) Looking forward to getting this live, again great work!
