### ISSUE TITLE
Debugging with VsCode

### ISSUE THREAD

**Issue by arihantdaga** [DivanteLtd/vue-storefront-api#117]
This is not an issue but a help needed topic. 
I was trying to understand the code and develop it further. And like most people i am using VSCode by default for javascript development. But i couldn't make debug work for me with the whole bable thing. 
Can anyone suggest me, how we can utilize vscode debugging  if anyone has figured that out already.

**Comment by arihantdaga** [comment]
Never Mind. I figured it out. Closing it.

**Comment by praneethmendu** [comment]
@arihantdaga hey I am facing similar issues, could you please post your solution
