### ISSUE TITLE
error: uncaughtException: Specified query type "Query" not found in document. 

### ISSUE THREAD

**Issue by tryonfly** [DivanteLtd/vue-storefront-api#121]
Hi, i'm trying to deploy vue-storefront in cloud environment (docker+kubernetes). I succeeded to deploy a workin example but after changes broking it, even turning back to the previous state doesnt resolve the problem.

First I launch elasticsearch+redis. At this point they are up and running. Elastic search gives this warning 
but i dont remember if it was there also before:

> [2018-10-01T15:12:28,214][WARN ][o.e.d.c.x.s.AbstractXContentParser] Expected a boolean [true/false] for property [has_options] but got [0]

Then i launch api (an image) which runs following commands:
```
yarn install
yarn build
node dist/index.js
```
At this point, (even if i dont make restore, migrate and database import with mage2vs, elastic search is already populated from previous database import) api should be running.

Vue-storefront-api starts to listen on 0.0.0.0:8080 but it gives me error: 

>  Extension mailchimp-subscribe registered under /ext/mailchimp-subscribe base URL
info: Winston logging library initialized.
Extension example-magento-api registered under /ext/example-magento-api base URL
Extension cms-data registered under /ext/cms-data base URL
error: uncaughtException: Specified query type "Query" not found in document. date=Mon Oct 01 2018 20:19:52 GMT+0000 (UTC), pid=1, uid=0, gid=0, cwd=/var/www, execPath=/usr/local/bin/node, version=v8.12.0, argv=[/usr/local/bin/node, /var/www/dist/index.js], rss=64294912, heapTotal=40284160, heapUsed=29084960, external=839586, loadavg=[0.603515625, 0.349609375, 0.365234375], uptime=6922854, trace=[column=17, file=/var/www/node_modules/graphql/utilities/buildASTSchema.js, function=null, line=133, method=null, native=false, column=null, file=null, function=Array.forEach, line=null, method=forEach, native=false, column=30, file=/var/www/node_modules/graphql/utilities/buildASTSchema.js, function=Object.buildASTSchema, line=126, method=buildASTSchema, native=false, column=28, file=/var/www/node_modules/graphql-tools/dist/schemaGenerator.js, function=buildSchemaFromTypeDefinitions, line=126, method=null, native=false, column=18, file=/var/www/node_modules/graphql-tools/dist/schemaGenerator.js, function=_generateSchema, line=49, method=null, native=false, column=20, file=/var/www/node_modules/graphql-tools/dist/schemaGenerator.js, function=makeExecutableSchema, line=62, method=null, native=false, column=53, file=/var/www/dist/index.js, function=null, line=96, method=null, native=false, column=30, file=module.js, function=Module._compile, line=653, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=664, method=.js, native=false, column=32, file=module.js, function=Module.load, line=566, method=load, native=false], stack=[Error: Specified query type "Query" not found in document.,     at /var/www/node_modules/graphql/utilities/buildASTSchema.js:133:17,     at Array.forEach (<anonymous>),     at Object.buildASTSchema (/var/www/node_modules/graphql/utilities/buildASTSchema.js:126:30),     at buildSchemaFromTypeDefinitions (/var/www/node_modules/graphql-tools/dist/schemaGenerator.js:126:28),     at _generateSchema (/var/www/node_modules/graphql-tools/dist/schemaGenerator.js:49:18),     at makeExecutableSchema (/var/www/node_modules/graphql-tools/dist/schemaGenerator.js:62:20),     at Object.<anonymous> (/var/www/dist/index.js:96:53),     at Module._compile (module.js:653:30),     at Object.Module._extensions..js (module.js:664:10),     at Module.load (module.js:566:32)]
Vue Storefront API started at http://0.0.0.0:8080 

**And then keeps logging this elastic search debug:**

> No additional data adapter for category
Entering HmacProcessor::process
POST /api/catalog/vue_storefront_catalog/category/_search?size=4000&from=0&sort=position%3Aasc&_source_include=children_data%2Cid%2Cchildren_count%2Csku%2Cname%2Cis_active%2Cparent_id%2Clevel%2Curl_key%2Cproduct_count 200 219.815 ms - 38095
Entering ProductProcessor::process
Taxes will be calculated for PL  false
Elasticsearch INFO: 2018-10-01T20:19:55Z
  Adding connection to http://elasticsearch:9200/

> Elasticsearch
 DEBUG: 2018-10-01T20:19:55Z
  starting request {
    "method": "POST",
    "path": "/vue_storefront_catalog/taxrule/_search",
    "body": {},
    "query": {}
  }
  
> Elasticsearch
 DEBUG: 2018-10-01T20:19:55Z
  Request complete

> Tax rate VAT23-PL = 23% found for PL / 
Tax rate VAT23-PL = 23% found for PL / 
Tax rate VAT23-PL = 23% found for PL / 
Tax rate VAT23-PL = 23% found for PL / 
Tax rate VAT23-PL = 23% found for PL / 
Tax rate VAT23-PL = 23% found for PL / 
Tax rate VAT23-PL = 23% found for PL / 
Tax rate VAT23-PL = 23% found for PL / 

I cant really get what causes the problem, so if you can take a look and give some feedback, it would be great. Thanks.

**Comment by lukeromanowicz** [comment]
Is the issue still up in 1.8.3?

**Comment by lukeromanowicz** [comment]
Closing due to OP inactivity.
