### ISSUE TITLE
Magento configuration in default.json

### ISSUE THREAD

**Issue by tryonfly** [DivanteLtd/vue-storefront-api#122]
There is a magento configuration part in default.json config, but in your documentation for production you don't talk about it at all. Neither in your medium post where you explain how to integrate it with magento. By default it points to/for example data set. One should modify this part or its there for just demo use?

```  
"magento2": {
    "url": "http://magento2.demo-1.xyz.com",
    "imgUrl": "http://localhost:8080/media/catalog/product",
    "assetPath": "/../var/magento2-sample-data/pub/media",
    "magentoUserName": "",
    "magentoUserPassword": "",
    "httpUserName": "",
    "httpUserPassword": "",
    "api": {
      "url": "http://demo-magento2.vuestorefront.io/rest",
      "consumerKey": "byv3730rhoulpopcq64don8ukb8lf2gq",
      "consumerSecret": "u9q4fcobv7vfx9td80oupa6uhexc27rb",
      "accessToken": "040xx3qy7s0j28o3q0exrfop579cy20m",
      "accessTokenSecret": "7qunl3p505rubmr7u1ijt7odyialnih9"
    }
  },
```

**Comment by Cyclonecode** [comment]
@tryonfly - There is a link which talks about this: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Totals%2C%20cart%2C%20orders%20sync%20with%20Magento.md

**Comment by pkarw** [comment]
Good point, Could You please add a link to the file in the production setup docs @Cyclonecode please?

**Comment by Cyclonecode** [comment]
@pkarw - Yes I will add this

**Comment by lukeromanowicz** [comment]
Looks like it already has been added to the docs
