### ISSUE TITLE
Cart update error

### ISSUE THREAD

**Issue by mateo2181** [DivanteLtd/vue-storefront-api#123]
Hello!
I am trying to add a product to the cart but I get error 500. 
**Request:** `curl -XPOST -H "Content-Type: application/json" --data '{"cartItem":{"sku":"Reel%20Frontal%208%20Rulemanes%207000","qty":1,"quoteId":"c2a9b2c17e35571610cdcc7ae5533b86"}}' http://localhost:8080/api/cart/update?token=aus912qjdik8bpy0y3vwi1v3bsmsbl8l&cartId=c2a9b2c17e35571610cdcc7ae5533b86`

**Response:**  {"code":500,"result":"Producto que desea agregar no está disponible."}

But the product exists because when I do 
`curl -XGET localhost:8080/api/stock/check?sku=Reel%20Frontal%208%20Rulemanes%207000` 
I get 200 response with qty > 0.

I am working with Magento 2.

**Magento Version:** 2.2.5
**Node Version:** 8.11.2
**Commit SHA:** 84011bf920d386769f14808d8ad93b3a806e3d59

Thanks!!

**Comment by pkarw** [comment]
For this request vsapi is just a proxy. His message is coming directly from Magento. Magento has lot of settings for stock management and maybe event if qty>0 it’s stoll below minimum qty for making product available. To be honest I don’t know ;) but it’s not in vsapi
