### ISSUE TITLE
Can't connect to redis server using standard mode

### ISSUE THREAD

**Issue by jahvi** [DivanteLtd/vue-storefront-api#137]
I'm trying to run an import from an M2 site using the `vs2mage import` command but I'm running into issues with the redis container.

**Steps to replicate**:

1. Clone fresh copy of `vue-storefront-api`
2. Copy `config/default.json` as `config/local.json`
3. Change magento2 settings (url, api credentials, etc)
4. Start docker containers `docker-compose -f docker-compose.yml -f docker-compose.nodejs.yml up -d`
5. Run import command `docker exec -it vue-storefront-api_app_1 yarn mage2vs import`

**Expected result**

It should finish importing entities to elasticsearch/redis without errors.

**Actual result**

It throws the following error:

```
error: uncaughtException: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379 date=Sun Nov 11 2018 13:30:27 GMT+0000 (UTC), pid=393, uid=0, gid=0, cwd=/var/www, execPath=/usr/local/bin/node, version=v8.12.0, argv=[/usr/local/bin/node, /var/www/node_modules/mage2vuestorefront/src/cli.js, reviews], rss=65208320, heapTotal=41844736, heapUsed=26356432, external=193979, loadavg=[0.16162109375, 0.09423828125, 0.07861328125], uptime=13868, trace=[column=14, file=net.js, function=TCPConnectWrap.afterConnect [as oncomplete], line=1191, method=afterConnect [as oncomplete], native=false], stack=[Error: Redis connection to 127.0.0.1:6379 failed - connect ECONNREFUSED 127.0.0.1:6379,     at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1191:14)]
```

I think this is because the container is trying to find the redis host in its own localhost `127.0.0.1:6379`, but it's not really there. Since the app container starts with the `depends_on: - redis...` option you can get the host using the `redis` hostname but when I change the redis host from "localhost" to "redis" in my `local.json` file it still tries to connect to localhost for some reason.

Using legacy mode works fine.

**Comment by pkarw** [comment]
Thanks! Seems like an configuration issue with mage2vs - well take a look at it

**Comment by pkarw** [comment]
Please retest

**Comment by jahvi** [comment]
Thanks! Can confirm it works now.
