### ISSUE TITLE
Unable to run in product due to regeneratorRuntim

### ISSUE THREAD

**Issue by hunterjamesio** [DivanteLtd/vue-storefront-api#156]
In order to get this running in production I had to add `@babel/polyfill` to the projects dev dependencies alongside adding `import '@babel/polyfill';` to the top of `src/index.js'. As guided by https://stackoverflow.com/questions/33527653/babel-6-regeneratorruntime-is-not-defined

Has anyone else come across this? Is this a viable solution and should I submit a PR?

**Comment by pkarw** [comment]
We're not supporting async/await yet - and it's not a bug. It's just how it was configured :) I see no reason why not to add the babel settings to support it. So You can create a PR - sure :)
