### ISSUE TITLE
Default image URL wrong running against bitnami/magento-docker

### ISSUE THREAD

**Issue by cmeyertons** [DivanteLtd/vue-storefront-api#157]
the default image base url in default.json is:
`https://magento.example.com/media/catalog/product`

while my Magento docker application only responds to images at:
`https://magento.example.com/pub/media/catalog/product`

is my configuration wrong?  is this something that has changed by default in Magento?

**Comment by lukeromanowicz** [comment]
@cmeyertons have you resolved the issue? In general, it should not matter what's the Magento server as far as it has all the required endpoints publicly accessible.

**Comment by lukeromanowicz** [comment]
Closing due to OP inactivity.
