### ISSUE TITLE
Product API returns prices for root store only

### ISSUE THREAD

**Issue by grimasod** [DivanteLtd/vue-storefront-api#162]
Since 1.6 there's an issue in the product API, where only root store prices are return by the render-list API request.

File: 

```/src/api/product.ts```

In the line

```javascript
productProxy.renderList(req.query.skus.split(','), req.query.currencyCode, req.query.storeId && parseInt(req.query.storeId) > 0 || 1).then(
```

The third parameter passed to renderList is converted to a boolean 

```javascript
req.query.storeId && parseInt(req.query.storeId) > 0 || 1
```

This causes prices for all stores to the those of the root store.

It should be the storeId, to get correct prices and other store specific data. The following will correct this:

```javascript
(req.query.storeId && parseInt(req.query.storeId) > 0) ? req.query.storeId : 1
```

**Comment by pkarw** [comment]
Thanks! Could You create a pull request with a fix, please?

**Comment by grimasod** [comment]
Sure. Should I make a bug-fix branch for the pull request? Or just on the develop branch? I'm a GitHub noob!

**Comment by pkarw** [comment]
@grimasod the Bug-fix branch + PR would be best option. Thanks!

**Comment by grimasod** [comment]
@pkarw "remote: Permission to DivanteLtd/vue-storefront-api.git denied to grimasod."
When I try to push the bug-fix branch

**Comment by pkarw** [comment]
@grimasod could You please report the Pull Request from Your fork (please do project fork instead of creating a branch)

**Comment by grimasod** [comment]
Thanks for your patience! I'm still learning. I've done that now. Hopefully it's correct. Let me know.
