### ISSUE TITLE
Elasticsearch not active before searching for product

### ISSUE THREAD

**Issue by Decntdefalt** [DivanteLtd/vue-storefront-api#187]
Categories in menu are not showing on first pageload.

It appears to me that elasticsearch is not active or it's being "activated" when you search for product "test" on https://techdrones.no. 

After clicking on the product in search, and clicking on "go back button", you'll see the categories finally appearing in the menu. 

On my other 2 projects https://logima.io and https://hoversport.no everything works fine and all projects have the same configuration and different indexes etc. 

What could be the cause?

**Comment by ludioao** [comment]
Do you find the solution?

**Comment by Decntdefalt** [comment]
> Do you find the solution?

Yeah! Precisely use Elasticsearch 5.6.0.

`curl -L -O https://artifacts.elastic.co/downloads/elasticsearch/elasticsearch-5.6.0.deb ; dpkg -i elasticsearch-5.6.0.deb ; /etc/init.d/elasticsearch start `

Works on my ubuntu instance.
