### ISSUE TITLE
import concurrency issue

### ISSUE THREAD

**Issue by yohanespradono** [DivanteLtd/vue-storefront-api#189]
I have hundreds of magento categories. when doing yarn mage2vs import, it async called all categories and some connections were closed because php-fpm children were not ready or exceeding limit.

```
{ message: 'read ECONNRESET',
  stack: 'Error: read ECONNRESET\n    at _errnoException (util.js:992:11)\n    at TCP.onread (net.js:618:25)',
  code: 'ECONNRESET',
  errno: 'ECONNRESET',
  syscall: 'read' }

```

is there an easy way to throttle the categories api call concurrent connection? I'm not familiar with nodejs world.

**Comment by pkarw** [comment]
Hi @yohanespradono. You might want to check the https://github.com/DivanteLtd/magento2-vsbridge-indexer native indexer.

In case of m2vs and category indexing - You can set the command line parameter `--extendCategories=false` to limit the number of concurrent requests.

Another option is to slightly refactor the `adapters/magento/category.js` to use [throthling helper](https://github.com/DivanteLtd/mage2vuestorefront/blob/07f3376966a86782f9d83c20ca177de9dbbc7de1/src/adapters/magento/product.js#L20) to queue the network calls

**Comment by yohanespradono** [comment]
i have refactored my category.js to use promise-throttle
