### ISSUE TITLE
Production Requirements

### ISSUE THREAD

**Issue by ludioao** [DivanteLtd/vue-storefront-api#199]
Hi there, 

I have a VM on Vultr with 2GB ram, 1 vCPU and 50gb disk space - with around 15 products and 3 categories.
I've a setup according by the production tutorial, but elastic search service is killing everytime and using about 1,3gb RAM and already configured with 512mb max heap.

What is the best requirements to run the vue project?

My magento installation is on another server.

Thanks

**Comment by pkarw** [comment]
Hi @ludioao; there are no official requirements for the servers but You can get some insights from reading https://medium.com/the-vue-storefront-journal/vue-storefront-performance-tests-and-architecture-ready-for-traffic-peaks-279c4c783412 - tests results + example configuration attached :)

**Comment by ludioao** [comment]
Hello @pkarw. 

I've drastically improve with the ssr cache... and now its working fine ;)
