### ISSUE TITLE
Typescript Support

### ISSUE THREAD

**Issue by ResuBaka** [DivanteLtd/vue-storefront-api#210]
This should be more for a discussion for changing the code to typescript.

My points would be:
* better intellisense for the IDE/editor you are using
* Less errors because of the type checks
These where two points which i have in mind and why i want to ask for it. 

Extensions would still be possible in Javascript which would then be not a 100% breaking change.

Maybe some one other has some other points why it shouldn't be done or that it is a good idea to move to typescript.

I am looking forward to what you guys have to say to it.

**Comment by lukeromanowicz** [comment]
@ResuBaka We would love to have TS in API, preferably with jest unit tests. However, at this point, there are some things with higher priority to be done so it will probably have to be delayed. We will definitely appreciate a PR :-)

**Comment by ResuBaka** [comment]
I can implement it and make a pr. 
It would only be good to know how much i should rewrite in ts or if i for first only should setup the tsconfig and the package.json so when someone wants to write in typescript that he can do it.

**Comment by lukeromanowicz** [comment]
I believe we should value quality over quantity so let's go with TS configuration and a few first files to start with and then another PRs with other segments of the API

**Comment by lukeromanowicz** [comment]
Will be released in 1.10. Rewriting API files to typescript will be done in #219
