### ISSUE TITLE
Change POST order response status code from 500 to 400 if order data is invalid.

### ISSUE THREAD

**Issue by AndreiBelokopytov** [DivanteLtd/vue-storefront-api#220]
Normally REST API should return 400 or similar status code if there was any issue related with received data.
For now VueStorefront API returns 500 status code for POST order request if a user entered invalid data, for example only numbers in the name field.
It's related to [2663](https://github.com/DivanteLtd/vue-storefront/issues/2663) Storefront issue

**Comment by lukeromanowicz** [comment]
Will be released as part of 1.9 update
