### ISSUE TITLE
API loading become very slow after updating to latest version of both VSF and VSF-API.

### ISSUE THREAD

**Issue by michhy** [DivanteLtd/vue-storefront-api#229]
I m still on developing mode, testing in local docker server, grabbing data from magneto host on AWS. 
Not sure why the API loading time is much longer than before. 

I have also enable PayPal extension and not sure is it the reason too.

**Comment by pkarw** [comment]
Thanks for noticing us however it’s very hard to help: please try to be more specific. Please do also check the Elastoc and Magento response times accordingly

**Comment by michhy** [comment]
Thank you for your hints, let me try to gether more information.
At least I know this is not a common issue.
