### ISSUE TITLE
Cart Error "You need to choose options for your item" after posting new products

### ISSUE THREAD

**Issue by rpss2** [DivanteLtd/vue-storefront-api#230]
Hi! When I post a new product and call productsdelta for update products, this error happens, but general import work perfectly. I verified JSON file for products and attributeCode attribute for object doesn't exists for product with error. The attributeCode in question is "size".

**Comment by pkarw** [comment]
Hi! Please provide us with your:
- magento version number
- vs version number
- make sure you did run “yarn db rebuild” after the import to set proper field types in elastic
