### ISSUE TITLE
the importer does not import cmspage and cmsblock like in mage2vuestorefront

### ISSUE THREAD

**Issue by toh82** [DivanteLtd/vue-storefront-api#235]
Within the scripts/mage2vs.js the import commands for importing cms parts are missing. Let's add them here, too. 

commands from mage2vuestorefront:
```
node --harmony cli.js blocks
node --harmony cli.js pages
```

This is the syntax how it could look like, @pkarw is that correct or am I mistaken?
```
return exec('node', [
  '--harmony',
  'node_modules/mage2vuestorefront/src/cli.js',
  'pages'
], { env: env, shell: true })

return exec('node', [
  '--harmony',
  'node_modules/mage2vuestorefront/src/cli.js',
  'blocks'
], { env: env, shell: true })
```

As we talked already I would volunteer to fix this issue right away @pkarw, tho it might be that I need a little hands on, about the code. 

---
- [ ] add the commands to the scripts/mage2vs.js
- [ ] update the readme file about it

**Comment by pkarw** [comment]
It looks like the right solution. The only thing is that somebody might not have the Snowdogs module installed; in that case we should display a proper error message - and that’s all :-)

**Comment by toh82** [comment]
Killed the old PR since it was outdated and branch was weird. New one will come soon also with check about the response from the cms extension

**Comment by toh82** [comment]
@pkarw new PR is ready. Let me know if the Idea about doing a try catch to be aware of missing extension or problems is okay. Also since I'm not able to run docker on my private machine (not windows pro) this code is not tested. Would be cool if you could run a testcase.
