### ISSUE TITLE
500 Internal Server Error when I tried to save zip code with three characters

### ISSUE THREAD

**Issue by alinadivante** [DivanteLtd/vue-storefront-api#253]
## Steps to reproduce the issue
1. Log in to your account
2. Go to My profile
3. Edit your profile → mark checkbox "I have company (...)"
4. In Zip-code* filed  enter only three numbers
5. Save it
6. Repeat steps 4-5 in "My shipping details" form

## Current behavior
500 Internal Server Error in dev console and there is no any pop-up for end-user.
![image](https://user-images.githubusercontent.com/36628922/58412353-95d87d00-8076-11e9-86b6-9904ce2603d8.png)
[localhost-1558951080710.log](https://github.com/DivanteLtd/vue-storefront-api/files/3223247/localhost-1558951080710.log)

` {"code":500,"result":[{"keyword":"minLength","dataPath":".customer.addresses[0].postcode","schemaPath":"#/properties/customer/properties/addresses/items/properties/postcode/minLength","params":{"limit":5},"message":"should NOT be shorter than 5 characters"}]} `

## Expected behavior
It should accept three characters and changes should be saved.

**Comment by alinadivante** [comment]
@lukeromanowicz Could you look at this?

**Comment by lukeromanowicz** [comment]
Thanks for your report. It will be fixed in 1.9.3
