### ISSUE TITLE
Use redis with authentication

### ISSUE THREAD

**Issue by Smolevich** [DivanteLtd/vue-storefront-api#257]
Hello!
Can i use directly or create custom settings for redis with authentication?
I see in [redis library](https://github.com/NodeRedis/node_redis#rediscreateclient) parameter `url`, which can be used for setting url to redis instance

**Comment by lukeromanowicz** [comment]
Yes, you can. Everything you set in config.redis goes directly to redis createClient method, so basicly you can add any redis option you like from the list available in docs https://www.npmjs.com/package/redis
