### ISSUE TITLE
getting 404 in console 

### ISSUE THREAD

**Issue by ganeshr28** [DivanteLtd/vue-storefront-api#26]
not able to view backend getting 404 error 
![screenshot from 2018-02-27 14-39-05](https://user-images.githubusercontent.com/32222445/36719754-03aefe3c-1bcc-11e8-95a9-6eabb34338e3.png)

browser image 
![screenshot from 2018-02-27 14-39-50](https://user-images.githubusercontent.com/32222445/36719797-1e8510e8-1bcc-11e8-8a35-7699bf645921.png)

**Comment by pkarw** [comment]
This is only the api. For the front end please install vue-storefront project

**Comment by ganeshr28** [comment]
@pkarw forntend is working fine but i not able to access backend

**Comment by pkarw** [comment]
This is only API; there is No admin panel; you need to integrate IT with Magento

**Comment by ganeshr28** [comment]
@pkarw ok thanks
