### ISSUE TITLE
Magento 1 bridge stock check always "out of stock"

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront-api#260]
No matter what, the products in cart are always out of stock and the `/api/stock/check?sku=xxx` always returns an empty object.

This seems to happen since the msi support for this endpoint:  https://github.com/DivanteLtd/vue-storefront-api/commit/8014d38751b75b83974e9c5a7ea8ddfa74df34e4#diff-dd5262a5a0e387fd010f9de167a52721

I changed this at the endpoint of the `platform/magento1/stock.js` and it is working again.

**Comment by lukeromanowicz** [comment]
Merged to develop. Thanks for your contribution.
