### ISSUE TITLE
API definition for platform abstraction

### ISSUE THREAD

**Issue by nkuehn** [DivanteLtd/vue-storefront-api#29]
Is there something more precise available as an API definition to plug a different backend Platform? 

There is an abstract implementation but since JS is dynamic it does not provide any explicit or implicit clue on the expected data models, response models, error behavior etc. 
https://github.com/DivanteLtd/vue-storefront-api/tree/master/src/platform/abstract  

Since it seems to be a 1:1 proxy of the extenal API an OpenAPI or similar definition would suffice, too (maybe even better since it would allow to build a compatible server side implementation that uses a lighter stack without an extra elasticsearch, redis etc (all of which is only necessary for backend platforms that are too bad to tackle the actual load in a stable way).

**Comment by pkarw** [comment]
@nkuehn that would be great (lighter stack)! Unfortunately I don't have the full specification of the calls.

This is currently a proxy of some methods from Magento2 API (http://devdocs.magento.com/swagger/) with some custom endpoints.
We used Magento2 data formats as a abstraction layer for further platforms (you can see how for example pimcore bridge works: https://github.com/DivanteLtd/pimcore2vuestorefront)

I belive that the best way to allow users to create their own implementations would be to:
- play with demo.vuestorefront.io and record the calls to https://demo.vuestorefront.io/api - where the vue-storefront-api is running
- generate the docs for these requests - it's all JSON api and the formats are pretty easy to understand

The next step will be to create this lightweight API

ps. Here it's the VS ElasticSearch data format described: https://github.com/DivanteLtd/vue-storefront/blob/master/doc/ElasticSearch%20data%20formats.md

Are you willing to perform this 1st step with API docs?
That will be great first PR to vue-storefront

**Comment by nkuehn** [comment]
Hi @pkarw, to be honest it's not really convincing to me that the APIs exposed are basically a mashup of a "de facto but not documented" subset of  a magento 2 snapshot version API plus raw elasticssearch access.   

Invensting time and effort in such a "moving target" definition that does not even have the same data structures e.g. for a product in a cart vs. a product in a search result just out of curiosity does not feel like a good investment of time until there's a client use case on the desk (I write here just out of private curiosity). 

Upgrading ES would change the definition, upgrading magento would change the definition, referencing or just using a different version of "smile-magento-elasticsearch" would change the definition etc.  You could "freeze" some version now but I am not able to practically do that in a quality way since I have zero experience with all these systems and the vue storefront.

**Comment by pkarw** [comment]
Hi @nkuehn, sure I get your point, although it’s not kind of moving target  you described. The entities (product, category etc) are unified etc

Sure we should add schema validation / service contracts and we surely will do this.

At first we’ll start describing the API requests and responses.

Thanks for pointing out this need, this will be very useful :)
Thanks!

**Comment by pkarw** [comment]
ps. We’re not using smile module for indexing the data; please take a look at: 
- our data indexer: https://github.com/DivanteLtd/mage2vuestorefront
- our official Magento commeng project for the indexer: https://github.com/magento-engcom/es-indexer/wiki
- https://github.com/magento-engcom/es-indexer/wiki
- and the docs: https://github.com/DivanteLtd/vue-storefront/tree/master/doc


As vue-storefront-api is a part of vue-storefornt - most of the docs are placed there
