### ISSUE TITLE
Error: Integrating Magento 2 with your local instance

### ISSUE THREAD

**Issue by NuruddinBadawi** [DivanteLtd/vue-storefront-api#291]
I'm trying to integrate with my Magento store

I add the Magento Api information 

I run this code `yarn mage2vs import`

I get error in each importing step

the error like this: 

` message: 'unable to verify the first certificate',`

![Screen Shot 2019-06-29 at 11 13 26 AM](https://user-images.githubusercontent.com/5736522/60381533-efa9d980-9a5e-11e9-93f1-841af05886a3.png)

node -v
v12.5.0

yarn -v
1.12.3

npm -v
6.9.0

what that mean ?

**Comment by NuruddinBadawi** [comment]
I think the issue from `node` I use this env to make it work
`NODE_TLS_REJECT_UNAUTHORIZED=0`

**Comment by pkarw** [comment]
Related to #288

**Comment by lukeromanowicz** [comment]
NODE_TLS_REJECT_UNAUTHORIZED will indeed make it work but it's unsafe to use and I highly recommend  not to use it. An alternative (one of many) was proposed in the issue mentioned above.

**Comment by NuruddinBadawi** [comment]
so how to solve it and what I have another options?
