### ISSUE TITLE
Restify instead of Express

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront-api#3]
http://restify.com/

Let's consider it because performance, stability and simplicity

**Comment by marshallswain** [comment]
I would be interested in helping build `vue-storefront-api` on top of FeathersJS.  Looking at the codebase, it seems like it would be a nice fit, and would keep the clean architecture you've already got going.  With the new event channels feature, Feathers would also add super-efficient realtime support at almost zero development cost.  Maybe `vue-storefront` could benefit from the huge selection of [FeathersJS database adapters](https://github.com/feathersjs/awesome-feathersjs#database), somehow.  We also have pre-built auth modules which support rest and realtime transports, if those come in handy somehow.  It's used quite extensively in production at multiple Fortune 100 companies.  (I can't give names, but If you use a smartphone, there's a pretty good chance, you're getting served by a Feathers-backed server :)  And it's fast: https://github.com/hbakhtiyor/node-frameworks-benchmark.  The Feathers client package, though not required, would potentially be of use on the front end, and I've also built `feathers-vuex` which implements some common redux best practices for integrating Feathers services with Vuex.

I've been a Feathers Team member for several years, and would love to get involved on this project, if you become interested.

**Comment by pkarw** [comment]
Hi, @marshallswain sounds great to me. It would be great to discuss the details of how You like to approach this challenge? We can have a Skype call next week or You can just a few thoughts on this in here.

To be honest, we haven't got any major `vue-storefront-api` refactoring tasks on our roadmap (the project is part of: https://github.com/DivanteLtd/vue-storefront), so as we're very eager to get this done (I see that the projects could be designed lot way better) we would need strong support from Your side to make it happen :)

**Comment by marshallswain** [comment]
Cool!  I will look more into detail of what it will take before we schedule a Skype call.

**Comment by pkarw** [comment]
Cool! Let me know when is best for you to speak

**Comment by DarkMukke** [comment]
Is there any decision on this yet ?
 I would love to help out with the api, although never worked with FeathersJS before.

**Comment by pkarw** [comment]
@marshallswain any news?

**Comment by DarkMukke** [comment]
We have given feather a go in another vue/nuxt project and it seems to be good for what it does,
there is a bit of a learning curve in the beginning as it does things a bit differently from other frameworks but on the other hand it comes with all the tools for mocking and wireframing every possible route before you even need to implement them
i'll take a look at what it would take to restructure the current VS api in feathers

**Comment by lukeromanowicz** [comment]
We are not planning to replace express anytime soon as there are too many projects based on current solution. It might be considered in 2.0 though.
