### ISSUE TITLE
ElasticSearch with HTTPS protocol won't work

### ISSUE THREAD

**Issue by cewald** [DivanteLtd/vue-storefront-api#303]
The configs have an option called `config.elasticsearch.protocol` which isn't used despite in the Mage2-Datapump. That means if I like to use an ES endpoint with HTTPS I need to put it directly into the host config value (`config.elasticsearch.host`). Do we then again still need this unused config or should it be integrated correctly.

For example: If I have anticipate the API configs as they are, using the this `config.elasticsearch.protocol` config property with the value `https` and add just the hostname without protocol to `config.elasticsearch.host` it wouldn't work. Because at some points the API will try to send HTTP requests to HTTPS.

For example here at https://github.com/DivanteLtd/vue-storefront-api/blob/develop/src/api/catalog.js#L67-L69
```javascript
if (!url.startsWith('http')) {
  url = 'http://' + url
}
```
This should be somethin like:
```javascript
if (!url.startsWith('http')) {
  url = config.elasticsearch.protocol + '://' + url
}
```

**Comment by pkarw** [comment]
Good point; could you please propose a PR for that?

**Comment by cewald** [comment]
Done ;)
