### ISSUE TITLE
o2m: `region` does not sync

### ISSUE THREAD

**Issue by francescosalvi** [DivanteLtd/vue-storefront-api#316]
Hello
while doing some tests with v1.9 I noticed that [o2m.js](https://github.com/DivanteLtd/vue-storefront-api/blob/master/src/platform/magento2/o2m.js#L143) only uses the field `region` as an alternative for performing the m2-directory lookup (in case `regionCode` is missing), but does _not_ forward the field alongside the other ones.

This leads to the scenario where, if **no** matching directory data is present in m2 db, the "free-text" region information is simply lost (will always end up with `regionId: 0, regionCode: ''` - [here](https://github.com/DivanteLtd/vue-storefront-api/blob/master/src/lib/countrymapper.js#L14))

From my tests (with m2.3.2), if passing all of `regionId`, `regionCode`, and `region`, if the Id and Code are populated they will still take precedence, with `region` only acting as a fallback; because of this I think a simple patch like the following could do:

```
diff --git a/src/platform/magento2/o2m.js b/src/platform/magento2/o2m.js
index 81cfc06..d09157a 100644
--- a/src/platform/magento2/o2m.js
+++ b/src/platform/magento2/o2m.js
@@ -176,6 +176,7 @@ function processSingleOrder(orderData, config, job, done, logger = console) {
                 "email": billingAddr.email,
                 "regionId":  mappedBillingRegion.regionId,
                 "regionCode": mappedBillingRegion.regionCode,
+                "region": billingAddr.region,
                 "company": billingAddr.company,
                 "vatId": billingAddr.vat_id
               },
@@ -197,6 +198,7 @@ function processSingleOrder(orderData, config, job, done, logger = console) {
               "email": shippingAddr.email,
               "regionId": mappedShippingRegion.regionId,
               "regionCode": mappedShippingRegion.regionCode,
+              "region": shippingAddr.region,
               "company": shippingAddr.company
             }
           } else {

```

**Comment by pkarw** [comment]
Thanks! can you propose a PR if this is a general prupose fix please?

**Comment by francescosalvi** [comment]
Hi @pkarw , I opened the PR
> if this is a general prupose fix 
from my tests, it should be general-purpose; I also checked the code responsible for the "fallback" logic (`\Magento\Customer\Model\Address\AbstractAddress::getRegion*`) for changes between 2.2.x and 2.3.x and didn't find any, so I assume this works fine with 2.2 as well..

**Comment by pkarw** [comment]
OK cool, can you please prepare a Pull Request from your fork @francescosalvi?

**Comment by francescosalvi** [comment]
@pkarw I think https://github.com/DivanteLtd/vue-storefront-api/pull/319 is ready to be merged?
