### ISSUE TITLE
Refactor the way Elastic client is being setup

### ISSUE THREAD

**Issue by pkarw** [DivanteLtd/vue-storefront-api#327]
Currently, we have have a code duplication with Elastic:
- migrations/.common.js
- platform/magento1/tax.js
- platform/magento2/tax.js

we should extract the Elastic client setup code to `../../helpers/elastic.js`

kind of:

```js
	const getElasticClient = (config) => {
        const esConfig = { // as we're runing tax calculation and other data, we need a ES indexer
          host: {
            host: config.elasticsearch.host,
            port: config.elasticsearch.port,
            protocol: config.elasticsearch.protocol
          },
          apiVersion: config.elasticsearch.apiVersion,
          requestTimeout: 5000
        }
        if (config.elasticsearch.user) {
          esConfig.httpAuth = config.elasticsearch.user + ':' + config.elasticsearch.password
        }
        return new es.Client(esConfig)	
	}
```

**Comment by simonmaass** [comment]
@pkarw is this deployed? If i look into current deployment i see that it doesnt use the protocol...

const esConfig = { // as we're runing tax calculation and other data, we need a ES indexer
          host: this._config.elasticsearch.host + ':' + this._config.elasticsearch.port,
          log: 'debug',
          apiVersion: this._config.elasticsearch.apiVersion,
          requestTimeout: 5000
        }

**Comment by pkarw** [comment]
@simonmaass please do check the `develop` branch
