### ISSUE TITLE
Problem with send data by order create

### ISSUE THREAD

**Issue by 99percent6** [DivanteLtd/vue-storefront-api#33]
Hello!
I have a problem - when sending an order in the o2m logs i see an error after sending the request to the endpoint "shipping information".
`error: API call failed: Please specify shipping method.
2018-04-02T11:48:47.557Z - error: Error placing an order Please specify shipping method. string`
But all need information sending:
`debug: Calling API endpoint: POST http://*****************/shipping-information token: 
info:  url=**********************/shipping-information, method=POST, Authorization=Bearer *********,  **shippingMethodCode=dpdcarrier, shippingCarrierCode=dpdcarrier**, extensionAttributes=undefined`
o2m tries to send the order five times, after each time this error.
But the most interesting thing is this: if I take the same data, the same endpoint, send the request via postman, and then resume sending the same order through o2m, it will go without problems.
What can it be? What is the problem?

**Comment by pkarw** [comment]
Hi @99percent6, this is strange. For the demo-magento2.vuestorefront.io (Magento 2.1) it works just fine. I had this issue few times but always after 2nd or 3rd probe works just fine.

Would be great if You can dig and find what causes the problem in here?

**Comment by 99percent6** [comment]
Hi, once more. I'm sorry that I was gone for a while. In my case it was problem with m2, more precisely with modules. It expected to recieve custom_attributes, but fom VSF sended extension_attributes. 
But I still do not understand why the order was sent through postman.

**Comment by 99percent6** [comment]
Hi, Piotr, yesterday we found a problem that sometimes resulted in an error sending the order.
This was due to the order of sending billing address and shipping address.
In o2m right order, but sometimes the shipping address comes first to Magento and then billing address. In that case we get an error.

**Comment by pkarw** [comment]
Good point, so You mean that probably we need to avoid the Promise.all here:
https://github.com/DivanteLtd/vue-storefront-api/blob/cec4207d8084c63cd506390bf99d91653416ae75/src/worker/order_to_magento2.js#L234

?

Could You please refactor it, test and create a pull request?

**Comment by 99percent6** [comment]
Yes
