### ISSUE TITLE
Some categories not imported/shown on vue storefront after importing

### ISSUE THREAD

**Issue by flavea** [DivanteLtd/vue-storefront-api#347]
Hello, I am importing products from magento, but the problem is some categories don't show up. Previously I am using 1.9.5, and then upgrading to 1.10.0, but the results are the same. Even using a fresh install of vue storefront api, the categories are still missing. Any idea how to debug or fix this? Importing using kubernetes jobs.

Here is the categories in magento:

![Screenshot from 2019-10-11 11-38-20](https://user-images.githubusercontent.com/22873843/66624741-a5b6bf00-ec1b-11e9-9b02-79fa7eb3bab3.png)

Here is the vue storefront menu

![Screenshot from 2019-10-10 11-10-22](https://user-images.githubusercontent.com/22873843/66624762-b6ffcb80-ec1b-11e9-91f0-3c721c970e9a.png)

and on sub category, only the category that doesn't have child categories shows up

![Screenshot from 2019-10-11 11-39-45](https://user-images.githubusercontent.com/22873843/66624916-3db4a880-ec1c-11e9-9310-f474225c75e1.png)

**Comment by pkarw** [comment]
Vue Storefront is not displaying disabled categories( grayed out in Magento tree) - it doesn't look like an issue to be perfectly honest :) VSF is displaying enabled, visible categories that contains 1+ products

**Comment by flavea** [comment]
@pkarw yes, but as you can see on my images categories such as 'Ruang Kerja' and 'Dekorasi Rumah' are enabled, visible, and has more than one product, but don't show up. the enabled children categories don't show up too. After doing importing several times, it was usually those two categories that disappeared, though there are times that it's another category that disappeared.
