### ISSUE TITLE
Allow acces to all Mage media through /img and /media endpoints

### ISSUE THREAD

**Issue by rzeka** [DivanteLtd/vue-storefront-api#348]
Backstory: we are using S3 for Magento media storage. Same bucket is mounted next to VSF api with S3fuse, so it can access static files. We want to use direct bucket URL in `config.magento2.imgUrl` to be able to query for other assets provided by Magento eg.: category images, slides provided by Magento slider module or payment/carrier logos.

We thought about overriding front modules' actions, but why do this if we can add a processor, that will prefix all catalog images with valid paths and then use direct media url in config. This will allow us to use api's `/media` and `/img` endpoints to query for any Magento media.

This feature will ease use of CDN as well.

We are working on this code right now in case PR is needed

---

Looks like, when I was writing the feature request, someone asked same thing on forums: https://forum.vuestorefront.io/t/get-category-image-mediaurl/678 :)

**Comment by pkarw** [comment]
Hi there. There is such a possibility even right now - from VS 1.11: https://github.com/DivanteLtd/vue-storefront/pull/3209/files

When swithcing it on please remember to change the related `vue-storefront-api` config to remove `catalog/product` from `magento2.imgUrl`
