### ISSUE TITLE
ImageMagick requirement

### ISSUE THREAD

**Issue by DarkMukke** [DivanteLtd/vue-storefront-api#35]
The documentation nor yarn warns of a dependency of ImageMagick.

if ImageMagick is not installed on the server or host, images cannot be resized.

**Comment by DarkMukke** [comment]
should there not be a fallback for other image libraries, or serve the image not resized if no image libraries are found ?

**Comment by DarkMukke** [comment]
Another solution would be to server the api on a docker instance and set the requirements ourselves,
install the dependencies as needed, which also reduces the access to ES to have a public port mapped

**Comment by pkarw** [comment]
You're right. Could you please take care of this (I mean - updating the docs that Imagemagick is required + maybe some warning message in the vue-storefront-api console?)

The fallback would probably require quite a lot of work - so I belive the warning + docs is enough

WDYT @DarkMukke ?

**Comment by DarkMukke** [comment]
I will take care of this.

On a second note, I am trying to rewrite src/api/img.js to use libvips , which is 5x faster (according to their docs) than imageMagik and does not have any system dependencies. Also looking at better image cache instead of using /tmp. Something that supports configurable invalidation and multiple engines. I considered ES as img storage for a while but until ES 6.4, blob storage type is not really worth it.

I am taking my time on this one as I do not have that much time but I think relying on a lib (imagable) that no longer exists (github 404) is a wrong move to begin with.

**Comment by pkarw** [comment]
Cool, fingers crossed for this!

**Comment by DavidRouyer** [comment]
https://github.com/lovell/sharp looks like a good candidate:
- It replaces ImageMagick with https://github.com/jcupitt/libvips which seems faster
- It's a node lib, so we can ditch our current wrapper for ImageMagick (less code)

**Comment by pkarw** [comment]
Related to: 
https://github.com/DivanteLtd/vue-storefront/issues/165

@DavidRouyer Would be great if You can take care of this

**Comment by DavidRouyer** [comment]
See #110
