### ISSUE TITLE
API errors are being ignored by Vue Storefront

### ISSUE THREAD

**Issue by cdshotels-liborpansky** [DivanteLtd/vue-storefront-api#378]
Hi, I noticed that there's no message returned after order confirmation:
![image](https://user-images.githubusercontent.com/51436802/70242195-b2b1e380-1770-11ea-8c10-cd03d9e51c9e.png)

I noticed that `apiError` function in src/lib/util.js file checks in [Error](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Error) object for `errorMessage` property, but Error has only `message` property.
```js
/**  Creates a api error status Express Response object.
 *  @param {express.Response} res  Express HTTP Response
 *  @param {number} [code=200]    Status code to send on success
 *  @param {json} [result='OK']    Text message or result information object
 */
export function apiError (res, errorObj, code = 500) {
  return apiStatus(res, errorObj.errorMessage ? errorObj.errorMessage : errorObj, errorObj.code ? errorObj.code : 500)
}
```

Correct code should be:
```js
/**  Creates a api error status Express Response object.
 *  @param {express.Response} res  Express HTTP Response
 *  @param {number} [code=200]    Status code to send on success
 *  @param {json} [result='OK']    Text message or result information object
 */
export function apiError (res, errorObj, code = 500) {
  return apiStatus(res, errorObj.message ? errorObj.message : errorObj, errorObj.code ? errorObj.code : 500)
}
```

Then error notification message is correctly shown:
![image](https://user-images.githubusercontent.com/51436802/70242755-a8dcb000-1771-11ea-8ee1-eabab04e3441.png)

**Comment by andrzejewsky** [comment]
@cdshotels-liborpansky Helo, thanks for reporting, do you want to create PR to that?

**Comment by cdshotels-liborpansky** [comment]
#383 PR created
