### ISSUE TITLE
error: API call failed: Product with SKU

### ISSUE THREAD

**Issue by marcelowu** [DivanteLtd/vue-storefront-api#396]
![72950196-5ed37c00-3d69-11ea-801c-6bed5986db98](https://user-images.githubusercontent.com/30912144/73012308-c387e880-3df4-11ea-9a1b-8789ac5ea7cc.png)

**Comment by pkarw** [comment]
It's not related to VSF itself please check your magento API credentials in the config file + magento2 error log
