### ISSUE TITLE
Elastic stock extension cannot connect to ElasticSearch

### ISSUE THREAD

**Issue by themreza** [DivanteLtd/vue-storefront-api#402]
I was looking at the `elastic-stock` extension but accessing the endpoint kept on failing.
Upon further inspection, it looks like the following problems exist:
* `indexName` does not exist (https://github.com/DivanteLtd/vue-storefront-api/blob/master/src/api/extensions/elastic-stock/index.js#L15)
* `product.hits` doesn't exist. Instead, `product.body.hits` should be used (https://github.com/DivanteLtd/vue-storefront-api/blob/master/src/api/extensions/elastic-stock/index.js#L22).

**Comment by pkarw** [comment]
Related: #389

**Comment by pkarw** [comment]
Related: #388

**Comment by didkan** [comment]
@themreza @pkarw 
This sounds a lot like what I came across when upgrading an api-extension from 1.10 to 1.11.
The problem was when using different ES versions. We solved it with a helper like this:
Credit should be awarded to @benjick 🍺
```
export function getHits (result) {
  if (result.body) { // differences between ES5 and ES7
    return result.body.hits
  } else {
    return result.hits
  }
}
```

**Comment by gibkigonzo** [comment]
This shouldn't be a problem anymore. instead `indexName` is now used `index` and we have helper to get `hits`
