### ISSUE TITLE
Serve .webp images

### ISSUE THREAD

**Issue by domideimel** [DivanteLtd/vue-storefront-api#409]
Serve images default as webp and as fallback with a parameter like`?no-webp` for Browsers that don't support the modern image format. Since you using ImageMagick to resize the images, you can convert them on the fly as well.

https://imagemagick.org/script/webp.php

**Comment by tonyisworking** [comment]
@domideimel It's using [sharp](https://github.com/lovell/sharp) and libvips

You can extend the current `image.js` functions to something like `return transformer.toFormat("webp").toBuffer()` to create webp images

**Comment by pkarw** [comment]
This feature should be implemented in `storefront-api` @ResuBaka can we copy this FR there and make this image format configurable instead?
