### ISSUE TITLE
Fielddata is disabled on text fields by default?

### ISSUE THREAD

**Issue by KevinGorjan** [DivanteLtd/vue-storefront-api#418]
Hi

When I want to fetch the products on the Category-page.
I receive the following error:

> Fielddata is disabled on text fields by default. Set fielddata=true on [pattern] in order to load fielddata in memory by uninverting the inverted index. Note that this can, however, use significant memory. Alternatively use a keyword field instead.

I looked up in our **elastic.schema.product.json**, but **"pattern": {"type": "text"}** is by default set. This issue happened right after the sync from M2 to ElasticSearch with vsf-bridge-module.

We are using ES5.6 and M2.3.4.

Thanks

**Comment by pkarw** [comment]
please change it to `keyword` and run `yarn db reindex`
