### ISSUE TITLE
Relation of this project with storefront-api

### ISSUE THREAD

**Issue by dkarlovi** [DivanteLtd/vue-storefront-api#427]
Currently there exists this project and https://github.com/DivanteLtd/storefront-api

The documentation there claims

> Storefront API originated from the vue-storefront-api project and is currently backing 30+ production sites, including: Zadig&Voltaire, Klebefieber, Wonect and others.

So, is this project obsolete and future development will be focused there? What exactly are the roadmaps of the two projects, how do they differ and which one is recommended for production use?

**Comment by simonmaass** [comment]
Storefront-API will become the new API backend starting from VSF1.13

**Comment by dkarlovi** [comment]
Thanks, that would be great to add as info to both projects! Closing.
