### ISSUE TITLE
Error [ERR_HTTP_HEADERS_SENT] || Cannot set headers after they are sent to the client

### ISSUE THREAD

**Issue by simonmaass** [DivanteLtd/vue-storefront-api#434]
Everytime the API tries to fetch an image that doesnt exist:

GET //xxxx/media/catalog/product/r/u/russka-aufstehkissen.jpg [404]

I get the following errors in the console on the VSF API:
![error](https://user-images.githubusercontent.com/32599710/79067806-63516600-7cc2-11ea-897c-9bf73389770e.png)

**Comment by gibkigonzo** [comment]
`/media` doesn't trigger `src/api/img.ts`
it is used only for `/img`
Do you have same error in terminal or only in sentry?
Is there more information in sentry like error stack?
Can you reproduce it on `develop` or `master` branch?
