### ISSUE TITLE
Error during installation  "node_modules/sharp: Command failed." 

### ISSUE THREAD

**Issue by o2bj** [DivanteLtd/vue-storefront-api#435]
Evn: 
- node 12.16.1  and i tried also with 10.20.1
- yarn 1.22.4
- npm 6.13.4
- Docker version 19.03.8
- docker-compose version 1.25.4
- i'm using fresh azure bitnami node server

bitnami@bitnami-node-bb81:/opt/bitnami/apps/vue-storefront-api$ docker-compose -f docker-compose.yml -f docker-compose.nodejs.yml up -d
Building app
Step 1/9 : FROM node:10-alpine
 ---> 947b2561f403
Step 2/9 : ENV VS_ENV prod
 ---> Using cache
 ---> 1b079d0ee8ca
Step 3/9 : WORKDIR /var/www
 ---> Using cache
 ---> 995ddfe0da52
Step 4/9 : RUN apk add --no-cache curl git
 ---> Using cache
 ---> 367f35370d6a
Step 5/9 : COPY package.json ./
 ---> Using cache
 ---> 1c44a2ec9cec
Step 6/9 : COPY yarn.lock ./
 ---> Using cache
 ---> 9b0ec5f036ee
Step 7/9 : RUN apk add --no-cache --virtual .build-deps ca-certificates wget &&     yarn install --no-cache &&     apk del .build-deps
 ---> Running in 94793196c7cf
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/main/x86_64/APKINDEX.tar.gz
fetch http://dl-cdn.alpinelinux.org/alpine/v3.11/community/x86_64/APKINDEX.tar.gz
(1/2) Installing wget (1.20.3-r0)
(2/2) Installing .build-deps (20200415.062410)
Executing busybox-1.31.1-r9.trigger
OK: 24 MiB in 25 packages
yarn install v1.22.4
[1/5] Validating package.json...
[2/5] Resolving packages...
[3/5] Fetching packages...
info fsevents@1.2.9: The platform "linux" is incompatible with this module.
info "fsevents@1.2.9" is an optional dependency and failed compatibility check. Excluding it from installation.
[4/5] Linking dependencies...
warning " > graphql-tools@1.2.3" has incorrect peer dependency "graphql@^0.8.0 || ^0.9.0 || ^0.10.0 || ^0.11.0".
[5/5] Building fresh packages...
error /var/www/node_modules/sharp: Command failed.
Exit code: 1
Command: (node install/libvips && node install/dll-copy && prebuild-install) || (node-gyp rebuild && node install/dll-copy)
Arguments:
Directory: /var/www/node_modules/sharp
Output:
info sharp Downloading https://github.com/lovell/sharp-libvips/releases/download/v8.8.1/libvips-8.8.1-linuxmusl-x64.tar.gz
Segmentation fault (core dumped)
gyp info it worked if it ends with ok
gyp info using node-gyp@5.1.0
gyp info using node@10.20.1 | linux | x64
gyp ERR! find Python
gyp ERR! find Python Python is not set from command line or npm configuration
gyp ERR! find Python Python is not set from environment variable PYTHON
gyp ERR! find Python checking if "python" can be used
gyp ERR! find Python - "python" is not in PATH or produced an error
gyp ERR! find Python checking if "python2" can be used
gyp ERR! find Python - "python2" is not in PATH or produced an error
gyp ERR! find Python checking if "python3" can be used
gyp ERR! find Python - "python3" is not in PATH or produced an error
gyp ERR! find Python
gyp ERR! find Python **********************************************************
gyp ERR! find Python You need to install the latest version of Python.
gyp ERR! find Python Node-gyp should be able to find and use Python. If not,
gyp ERR! find Python you can try one of the following options:
gyp ERR! find Python - Use the switch --python="/path/to/pythonexecutable"
gyp ERR! find Python   (accepted by both node-gyp and npm)
gyp ERR! find Python - Set the environment variable PYTHON
gyp ERR! find Python - Set the npm configuration variable python:
gyp ERR! find Python   npm config set python "/path/to/pythonexecutable"
gyp ERR! find Python For more information consult the documentation at:
gyp ERR! find Python https://github.com/nodejs/node-gyp#installation
gyp ERR! find Python **********************************************************
gyp ERR! find Python
gyp ERR! configure error
gyp ERR! stack Error: Could not find any Python installation to use
gyp ERR! stack     at PythonFinder.fail (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:307:47)
gyp ERR! stack     at PythonFinder.runChecks (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:136:21)
gyp ERR! stack     at PythonFinder.<anonymous> (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:179:16)
gyp ERR! stack     at PythonFinder.execFileCallback (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/find-python.js:271:16)
gyp ERR! stack     at exithandler (child_process.js:301:5)
gyp ERR! stack     at ChildProcess.errorhandler (child_process.js:313:5)
gyp ERR! stack     at ChildProcess.emit (events.js:198:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:246:12)
gyp ERR! stack     at onErrorNT (internal/child_process.js:415:16)
gyp ERR! stack     at process._tickCallback (internal/process/next_tick.js:63:19)
gyp ERR! System Linux 4.15.0-1075-azure
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /var/www/node_modules/sharp
gyp ERR! node -v v10.20.1
gyp ERR! node-gyp -v v5.1.0
gyp ERR! not ok
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
ERROR: Service 'app' failed to build: The command '/bin/sh -c apk add --no-cache --virtual .build-deps ca-certificates wget &&     yarn install --no-cache &&     apk del .build-deps' returned a non-zero code: 1

**Comment by gibkigonzo** [comment]
I couldn't reproduce this, it seems like you are missing python. Can you check this Dockerfile https://github.com/DivanteLtd/storefront-api/blob/develop/docker/storefront-api/Dockerfile?

**Comment by o2bj** [comment]
problem fixed, what i done : 

1. nvm install 10.16.0
2. deleting folder node_modules 
3. i manually add "sharp" sharp - yarn add sharp -W 

But now my server is gone after "docker-compose up" for "vue-strorefronend" after 30 min at 96% server stop responding. 

How can debug what went wrong? 

Now also trying install vue-strorefront locally on windows 

But installation freezes on "Starting storefront server..." with no errors messages. 

```
? Would you like to use https://demo.vuestorefront.io as the backend? Yes
? Please provide path for images endpoint https://demo.vuestorefront.io/img/

 Trying to create log files...

 Creating storefront config 'config/local.json'...

 Build storefront npm...

 Starting storefront server...
```
