### ISSUE TITLE
Path `src/lib/ not compiled properly

### ISSUE THREAD

**Issue by jissereitsma** [DivanteLtd/vue-storefront-api#440]
When running `yarn build` and then `yarn start`, my environment (Node 10.19.0) is bumping into an issue, where all of the source is compiled successfully. However, in the PM2 logs there is an error `SyntaxError: Unexpected identifier` line 1 of `src/db.js` with a simple import: `import Redis from 'redis'`. Interestingly, this error does not occur at all with `yarn dev`, but only occurs when compiling the source and then running it using PM2.

In the end, the fix I used was the following. In the file `src/db.js`, I replaced the following lines:
```js
import config from 'config'
import * as redis from 'src/lib/redis'
import * as elastic from 'src/lib/elastic'
```
with:
```js
import config from 'config'
import * as redis from './lib/redis'
import * as elastic from './lib/elastic'
```

Any ideas?

**Comment by jissereitsma** [comment]
This might very well be related to https://github.com/DivanteLtd/vue-storefront-api/issues/437

**Comment by gibkigonzo** [comment]
yes, thats the same problem https://github.com/DivanteLtd/vue-storefront-api/pull/439
