### ISSUE TITLE
FetchError in request to ES: FetchError: invalid json response body

### ISSUE THREAD

**Issue by 1070rik** [DivanteLtd/vue-storefront-api#442]
## Current behavior
Sometimes (completely random) the API will just return a blank page when it's supposed to return an elasticsearch response. This will cause an error page and the error to be logged to our loggin software.
In the last 3 weeks this has happened about 23.5k times so it happens quite often.

I saw that a new API project (storefront-api) will be used for a future release of VSF but I can't test if it also happens there because putting that API on a production environment and changing all our api extensions is just too much work.

## Expected behavior
It should get a valid response or request it again if the data was invalid.

## Steps to reproduce the issue
This only happens on a production API and it doesn't output any errors to the logs. It just returns a 200 response with a blank page.
The most occurrences have happened on this API endpoint: 

> api/catalog/vue_storefront_magento_1/attribute/_search 

## Can you handle fixing this bug by yourself?

- [ ] YES
- [X] NO

## Which [Release Cycle](https://docs.vuestorefront.io/guide/basics/release-cycle.html) state this refers to? Info for developer.
Pick one option.

- [ ] This is a bug report for test version on https://test.storefrontcloud.io - In this case Developer should create branch from `develop` branch and create Pull Request `2. Feature / Improvement` back to `develop`.
- [ ] This is a bug report for current Release Candidate version on https://next.storefrontcloud.io - In this case Developer should create branch from `release` branch and create Pull Request `3. Stabilisation fix` back to `release`.
- [X] This is a bug report for current Stable version on https://demo.storefrontcloud.io and should be placed in next stable version hotfix - In this case Developer should create branch from `hotfix` or `master` branch and create Pull Request `4. Hotfix` back to `hotfix`.

## Environment details

- Browser: Chrome 81.0.4044.129
- OS: Mac OS 10.15.1
- Node: V10.19.0
- Code Version: V1.11.1

**Comment by gibkigonzo** [comment]
@1070rik thanks for reporting, this is problem related to vsf-api, so I moved it here

**Comment by pkarw** [comment]
This could be related to #393

**Comment by 1070rik** [comment]
We're running 1.11.1 and magento 2.3.5 and the error hasn't occurred in 3 weeks. Almost seems like this was caused by a value in ES from the VSBrdige.

**Comment by ResuBaka** [comment]
@1070rik is it always an URL with the prefix "api/catalog/" or does it happen to other endpoints to e.g. calls that do request against magento or custom endpoints?

**Comment by 1070rik** [comment]
@ResuBaka It was always on "api/catalog/"

**Comment by ResuBaka** [comment]
Then maybe try to update to version 1.12.1 which has [this](https://github.com/DivanteLtd/vue-storefront-api/pull/471/files) patch in it or just directly try it in the code base if it fixes it.

Other wise are there any errors that may happen at the same time, which can be seen in some logs (Error log or Standard log)?

When there are some kind of log messages that I could try to look for in the logs from where I work maybe we have the problem there, too. So I can try to find it in there too and check it there a bit out.

**Comment by 1070rik** [comment]
Oh sorry I think you misunderstood my comment. The issue seems to be fixed. I haven't gotten any reports of it in our bug tracking software for the last 3 weeks (around the time when we updated to magento 2.3.5 and updated vsbridge too). I think the issue can be closed now, right?

**Comment by ResuBaka** [comment]
Sry, I miss read it then. So thanks for the Info that is gone.

But you may still want to look into the fix, as it fixes a memory leak as creating a new ES clients for every request :smile:.
