### ISSUE TITLE
Deployment to remote redis fails, it always takes the default redis://127.0.0.1:6379

### ISSUE THREAD

**Issue by tobkle** [DivanteLtd/vue-storefront-api#46]
```bash
yarn migrate 
````

fails, as it doesn't find a remote redis host, due to config/default.json or its copy in config/local.json

```js
	"kue": {},
	"redis": {
		"host": "127.0.0.1",
		"port": 6379
	},
```

instead of...

```js
	"kue": {
	     "redis": {
		  "host": "redis.example.com",
		  "port": 6379
	    },
        },
```

**Comment by pkarw** [comment]
You're right. Migrations get the config.kue.redis nog config.redis. I've aligned it to one option:
https://github.com/DivanteLtd/vue-storefront-api/commit/a3c0c64c0119d74d4ba5f545b36317afb642e325

Is this the solution You expected?

**Comment by pkarw** [comment]
OK I've eventually got to https://github.com/DivanteLtd/vue-storefront-api/commit/48abe04eef11f441aeb6061310d95b09ab897b92

Which seems even more straightforward for the developer/user
