### ISSUE TITLE
order using redis queues (kue)

### ISSUE THREAD

**Issue by mwalol** [DivanteLtd/vue-storefront-api#469]
hi,

i have set useServerQueue to true to process the order's via the queue redis.

the problem i got is that i always get Success page when i place order even if the card is rejected by the gateway processor, i checked the order.js api and i can confirm that the err is always returned as null :

fork-vue-storefront-api/src/api/order.ts

```
let queue = kue.createQueue(Object.assign(config.kue, { redis: config.redis }));
        const job = queue.create('order', incomingOrder).save((err) => {
          //err is always null
          if (err) {
            console.error(err)
            apiError(res, err);
          } else {
            apiStatus(res, job.id, 200);
          }
 })
```

**Comment by pkarw** [comment]
Unfortunately you can't return statuses to the client with this offline mode order queue. please do use `directBackendSync` option for placing orders to avoid situation like this
