### ISSUE TITLE
New productsEquals in o2m does not work

### ISSUE THREAD

**Issue by revlis-x** [DivanteLtd/vue-storefront-api#494]
The changes introduced in https://github.com/DivanteLtd/vue-storefront-api/pull/480/files to compare products do not work as intended! The check does always seem to return true which messs up orders in all different kind of ways (wrong quantities, order not passing, b/c of wrong product options etc. as products get overwritten with each other and so on).

Reproduce on https://demo.storefrontcloud.io which has API in 1.12.2 running.
1. Put 2 different items in cart with different quantities and place order.
2. Either order fails completely ('please choose product option') or quantites of one product got overwritten by the other.
-> you see 'wrong qty' in api-logs to debug this.

**Comment by gibkigonzo** [comment]
@revlis-x So sorry :( I've made stupid mistake. I've exported productChecksum as productsEquals in vsf-utilities. Please update vsf-utilities to 1.0.2.
