### ISSUE TITLE
Disable cache

### ISSUE THREAD

**Issue by leon0v** [DivanteLtd/vue-storefront-api#66]
Hi :)

How can you temporarily disable all caching (in Elastic Search/Redis). For testing purposes.

**Comment by pkarw** [comment]
ElasticSearch is used as primary product catalog database it’s not a cache 

Redis is being used just in the mage2vs process 

Maybe let’s start with the reasoning for that - that’s your need?

**Comment by leon0v** [comment]
Yeah but i thought elasticsearch does cache the response for frequent queries?

**Comment by pkarw** [comment]
Ok, you’re right it does! Please take a look at this:
https://www.elastic.co/guide/en/elasticsearch/reference/current/query-cache.html

**Comment by leon0v** [comment]
Thanks :)
