### ISSUE TITLE
Image size calculation loads the processor.

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront-api#69]
Hey, Guys. In production VS i found issue with multiple processes calculation check image size

https://github.com/DivanteLtd/vue-storefront-api/blob/de739784a9ebc32a1e744ae062cf5d73f4b7840a/src/api/imageable/lib/request-handler.js#L163

**Comment by pkarw** [comment]
Maybe we should switch image able to some other solution? It’s far from ideal.

Could you please do some quick research on how to replace it?

Could You also please work-around this issue (maybe some internal/infunction in memory cache would be sufficient)?

Anyway, thanks for finding this one!
