### ISSUE TITLE
Incorrect sequence for the npm run setup

### ISSUE THREAD

**Issue by dimasch** [DivanteLtd/vue-storefront-api#8]
Have a nice day!
We have the incorrect sequence for the "npm run setup" cmd:
[https://github.com/DivanteLtd/vue-storefront-api/blob/master/package.json](url)

accordance by docs [https://github.com/DivanteLtd/vue-storefront/blob/master/doc/Installing%20on%20Linux%20and%20MacOS.md](url)

Actual result:
`npm run migrate; npm run restore`

Expected result:
`npm run restore; npm run migrate`

**Comment by pkarw** [comment]
Thanx! Fixed!
