### ISSUE TITLE
Example configuration clarification

### ISSUE THREAD

**Issue by daaru00** [DivanteLtd/vue-storefront-api#81]
Hi,

seems there is a little bit of mess in configuration file [default.json](https://github.com/DivanteLtd/vue-storefront-api/blob/master/config/default.json#L39) under `storeViews` property:
```json
{
  "storeViews": {
    "multistore": true,
    "mapStoreUrlsFor": [
      "de",
      "it"
    ],
    "de": {
      "storeCode": "de",
      "disabled": true,
      "storeId": 3,
      "name": "German Store",
      "url": "/de",
      "elasticsearch": {
        "host": "localhost:8080/api/catalog", <-----
        "index": "vue_storefront_catalog_de"
       },
```
what does `elasticsearch.host` refer to? seems not a elasticsearch path, and port is different from root elasticsearch property:
```json
{
  "server": {
    "host": "localhost",
    "port": 8080
  },
  "elasticsearch": {
    "host": "localhost", <-----
    "port": 9200, <-----
    "user": "elastic",
    "password": "changeme",
    "indices": [
      "vue_storefront_catalog",
      "vue_storefront_catalog_de",
      "vue_storefront_catalog_it"
    ]
},
```
how `storeViews.de.elasticsearch.host` configuration is used?

**Comment by pkarw** [comment]
Both forms of URL works fine - so not worry about it. By default the `storeviews.<storeCode>.elasticsearch` points to the same host like the default with different index. I can imagine the situation that the host differs - and You like to have english or german or whatever version on separate Elastic cluster. This option is just for that
