### ISSUE TITLE
Doesnt pull a package while docker-compose up

### ISSUE THREAD

**Issue by priyamukka** [DivanteLtd/vue-storefront-api#84]
vue-storefront-api# docker-compose up
Building kibana
Step 1/3 : FROM docker.elastic.co/kibana/kibana:5.6.9
5.6.9: Pulling from kibana/kibana
469cfcc7a4b3: Pull complete
dbf532e807c5: Pull complete
2fc6a7ee8a3a: Pull complete
aebda185619a: Pull complete
e71a1432017d: Pull complete
5d9b6f46e6f2: Pull complete
0fe8dbe6804f: Waiting

it kept waiting on this package even over night.

**Comment by pkarw** [comment]
This is strange, I'm not sure a docker expert; probably You need to refresh docker cache or sth (https://forums.docker.com/t/how-to-delete-cache/5753) ?

It doesn't seem to be related to Vue Storefront - i've tested docker file even today and it went just fine
