### ISSUE TITLE
[QUESTION] How to run a server without using docker in windows env?

### ISSUE THREAD

**Issue by valluminarias** [DivanteLtd/vue-storefront-api#93]
My machine is not capable of running docker environment, is there any way to run without using docker?

**Comment by pkarw** [comment]
This mode is unfortunately not officially. However, You could probably install Elastic + Redis locally + setup `vue-storefront-api/config` + `vue-storefront/config` accordingly to make it happen

**Comment by AndileCartist** [comment]
Is that all i need?
